# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee9fcf94a6d9b50e33743a397d7ffea66556b5961adb840166b8a824a93cd8d205e401d2cbf70898fa366640e69e739338bf37a1a4bbc74e387e1c4cb3e402ac

test:
  secret_key_base: 72e04bb68028e9081b38b127e0a32e37f5ac8b600f4dd9d287bada784e67bedad2d62fb46c07e1219299508987962ae96ee0781a4f066e9773f970c81e5362a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
